### ISSUE TITLE
Rspec tests fail in OS X for Ruby version 1.9.3

### ISSUE THREAD

**Issue by abinashmeher999** [symengine/symengine.rb#18]
The travis-ci build for OS X terminates with the following error message.
```
bundle exec rspec

/Users/travis/gems/symengine-0.1.0/lib/symengine.rb:1:in `require': cannot load such file -- symengine/symengine (LoadError)

	from /Users/travis/gems/symengine-0.1.0/lib/symengine.rb:1:in `<top (required)>'

	from /Users/travis/gems/symengine-0.1.0/spec/spec_helper.rb:16:in `require_relative'

	from /Users/travis/gems/symengine-0.1.0/spec/spec_helper.rb:16:in `<top (required)>'

	from /Users/travis/gems/symengine-0.1.0/spec/arit_spec.rb:1:in `require'

	from /Users/travis/gems/symengine-0.1.0/spec/arit_spec.rb:1:in `<top (required)>'
```
Complete log [here](https://gist.github.com/abinashmeher999/67652af1f0e94b87d897).

**Comment by isuruf** [comment]
@abinashmeher999, any updates on this?

**Comment by abinashmeher999** [comment]
The OS X system that I had was an office computer and had it with me for a short duration. Couldn't find out much about this.

**Comment by genya0407** [comment]
I have the same error as @abinashmeher999's one  in my local mac osx.

It seems that any other gems with native extensions doesn't have '*.so' binary file, but has '*.bundle' binary file.
I'm not sure, but I think that building native extension on osx might need some extra cmake configuration to generate '.bundle' file.

In addition, in my environment, `load '/Users/sangenya/.rbenv/versions/2.3.0-dev/lib/ruby/gems/2.3.0/gems/symengine-0.0.2/lib/symengine/symengine.so'` fails with the following error:

```
SyntaxError: /Users/sangenya/.rbenv/versions/2.3.0-dev/lib/ruby/gems/2.3.0/gems/symengine-0.0.2/lib/symengine/symengine.so:1: invalid multibyte char (UTF-8)
    from (irb):2:in `load'
    from (irb):2
    from /Users/sangenya/.rbenv/versions/2.3.0-dev/bin/irb:11:in `<main>'
```

Thanks.
